name: Prepare Litepaper PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command
      - name: Prepare PDF file
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'introduction/*.md'
      
      # Try to push the file to the repo
      - name: Copy file
        run: cp -p ${{ steps.publish-document.outputs.pdf }} ./Growr-litepaper.pdf
        
      - name: Add to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add new Litepaper PDF'
          add: './Growr-litepaper.pdf --force'
      
      # Concat MD files
      - name: Concat document files
        uses: bayssmekanique/action-md-concat@v1.1.0
        with:
          srcDir: './introduction'
          destFile: './litepaper/Growr-litepaper.md'
      
      - name: Add to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Add new Litepaper MD'
          add: './litepaper/Growr-litepaper.md --force'
