name: Prepare Protocol Spec PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'components/**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Concat MD files
      - name: Concat document files
        uses: bayssmekanique/action-md-concat@v1.1.0
        with:
          srcDir: './components'
          destFile: './litepaper/Growr-spec.md'
  
      - name: Convert MD to PDF
        uses: baileyjm02/markdown-to-pdf@v1.1.0
        with:
          input_dir: litepaper
          output_dir: litepaper
          images_dir: images
          image_import: ../images
          build_html: true
          theme: assets/css/whitepaper.css
          extend_default_theme: true

      - name: Add to repo
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Add new Litepaper PDF'
          add: './litepaper/Growr-spec.pdf ./litepaper/Growr-spec.html --force'
